```code
3.1_subset
├─hosp
│      admissions.csv.gz
│      diagnoses_icd.csv.gz
│      drgcodes.csv.gz
│      d_hcpcs.csv.gz
│      d_icd_diagnoses.csv.gz
│      d_icd_procedures.csv.gz
│      d_labitems.csv.gz
│      emar.csv.gz
│      emar_detail.csv.gz
│      hcpcsevents.csv.gz
│      labevents.csv.gz
│      microbiologyevents.csv.gz
│      omr.csv.gz
│      patients.csv.gz
│      pharmacy.csv.gz
│      poe.csv.gz
│      poe_detail.csv.gz
│      prescriptions.csv.gz
│      procedures_icd.csv.gz
│      provider.csv.gz
│      services.csv.gz
│      transfers.csv.gz
│
└─icu
        caregiver.csv.gz
        chartevents.csv.gz
        d_items.csv.gz
        icustays.csv.gz
        ingredientevents.csv.gz
        inputevents.csv.gz
        outputevents.csv.gz
        procedureevents.csv.gz
```

In [1]:
from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------------------
# Configs
# ------------------------------------------------------------------------------
ROOT = Path("/content/drive/MyDrive/DAHS/datasets/3.1_subset")

HOSP_DIR = ROOT / "hosp"
ICU_DIR = ROOT / "icu"

print("File exist?")
print(ROOT.exists())
print(HOSP_DIR.exists())
print(ICU_DIR.exists())
print("==============================================")


# ------------------------------------------------------------------------------
# Load `icustays.csv.gz`
# ------------------------------------------------------------------------------
icustays_path = ICU_DIR / "icustays.csv.gz"
icustays = pd.read_csv(icustays_path)

print("`icustays.csv.gz` shape: ", icustays.shape)
print("columns: ", icustays.columns.tolist())
print("==============================================")
print(icustays.head())
print("==============================================")
print("Unique subject_id(환자 수):", icustays["subject_id"].nunique())
print("Unique hadm_id(병원 입원 episode):", icustays["hadm_id"].nunique())
print("Unique stay_id(그 안의 ICU stay):", icustays["stay_id"].nunique())

File exist?
True
True
True
==============================================
`icustays.csv.gz` shape:  (3000, 8)
columns:  ['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit', 'intime', 'outtime', 'los']
==============================================
   subject_id   hadm_id   stay_id  \
0    10001884  26184834  37510196
1    10002428  23473524  35479615
2    10002428  28662225  38875437
3    10004733  27411876  39635619
4    10023486  25262533  31361200

                                     first_careunit  \
0                Medical Intensive Care Unit (MICU)
1                Medical Intensive Care Unit (MICU)
2                Medical Intensive Care Unit (MICU)
3  Medical/Surgical Intensive Care Unit (MICU/SICU)
4                               Trauma SICU (TSICU)

                                      last_careunit               intime  \
0                Medical Intensive Care Unit (MICU)  2131-01-11 04:20:05
1                Medical Intensive Care Unit (MICU)  2156-05-11 14:49:34
2                Medical Intensive Care Unit (MICU)  2156-04-19 18:11:19
3  Medical/Surgical Intensive Care Unit (MICU/SICU)  2174-12-04 11:28:24
4                               Trauma SICU (TSICU)  2151-06-06 14:06:06

               outtime        los
0  2131-01-20 08:27:30   9.171817
1  2156-05-22 14:16:46  10.977222
2  2156-04-26 18:58:41   7.032894
3  2174-12-12 20:03:01   8.357373
4  2151-06-13 22:03:23   7.331447
==============================================
Unique subject_id(환자 수): 2790
Unique hadm_id(병원 입원 episode): 2881
Unique stay_id(그 안의 ICU stay): 3000

In [2]:
# ------------------------------------------------------------------------------
# Load `patients/admissions.csv.gz` & check item matches well
# ------------------------------------------------------------------------------
patients_path = HOSP_DIR / "patients.csv.gz"
admissions_path = HOSP_DIR / "admissions.csv.gz"
patients = pd.read_csv(patients_path)
admissions = pd.read_csv(admissions_path)

print("==============================================")
print("patients shape   :", patients.shape)
print("admissions shape :", admissions.shape)
print("==============================================")
print("patients columns:")
print(patients.columns.tolist())
print("\nadmissions columns:")
print(admissions.columns.tolist())
print("==============================================")
print("icustays에 있는 subject_id가 patients에 모두 존재하는지?")
missing_subject = (set(icustays["subject_id"]) - set(patients["subject_id"]))
missing_hadm = (set(icustays["hadm_id"]) - set(admissions["hadm_id"]))
print("missing_subject:", len(missing_subject))
print("missing_hadm  :", len(missing_hadm))
print("==============================================")

==============================================
patients shape   : (2790, 6)
admissions shape : (2881, 16)
==============================================
patients columns:
['subject_id', 'gender', 'anchor_age', 'anchor_year', 'anchor_year_group', 'dod']

admissions columns:
['subject_id', 'hadm_id', 'admittime', 'dischtime', 'deathtime', 'admission_type', 'admit_provider_id', 'admission_location', 'discharge_location', 'insurance', 'language', 'marital_status', 'race', 'edregtime', 'edouttime', 'hospital_expire_flag']
==============================================
icustays에 있는 subject_id가 patients에 모두 존재하는지?
missing_subject: 0
missing_hadm  : 0
==============================================

In [3]:
# ------------------------------------------------------------------------------
# Load `chartevents.csv.gz` & check event matches well
# ------------------------------------------------------------------------------
chartevents_path = ICU_DIR / "chartevents.csv.gz"
chartevents = pd.read_csv(chartevents_path)

print("==============================================")
print("chartevents shape:", chartevents.shape)
print("columns:")
print(chartevents.columns.tolist())
print("==============================================")
print(chartevents.head())

==============================================
chartevents shape: (31295077, 11)
columns:
['subject_id', 'hadm_id', 'stay_id', 'caregiver_id', 'charttime', 'storetime', 'itemid', 'value', 'valuenum', 'valueuom', 'warning']
==============================================
   subject_id   hadm_id   stay_id  caregiver_id            charttime  \
0    10001884  26184834  37510196        2091.0  2131-01-18 04:19:00
1    10001884  26184834  37510196        2091.0  2131-01-18 04:19:00
2    10001884  26184834  37510196        2091.0  2131-01-18 04:19:00
3    10001884  26184834  37510196        2091.0  2131-01-18 04:19:00
4    10001884  26184834  37510196        2091.0  2131-01-18 04:19:00

             storetime  itemid                   value  valuenum valueuom  \
0  2131-01-18 05:19:00  227944              3 rails up       NaN      NaN
1  2131-01-18 05:19:00  227945                     On        NaN      NaN
2  2131-01-18 05:19:00  227946                    Done       NaN      NaN
3  2131-01-18 05:19:00  227947  Treatment interference       NaN      NaN
4  2131-01-18 05:19:00  227948               Soft limb       NaN      NaN

   warning
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0

In [4]:
icu_stay_ids = set(icustays["stay_id"].dropna().unique())
chart_stay_ids = set(chartevents["stay_id"].dropna().unique())

missing_in_icustays = chart_stay_ids - icu_stay_ids

print("==============================================")
print("Unique stay_id in icustays    :", len(icu_stay_ids))
print("Unique stay_id in chartevents :", len(chart_stay_ids))
print("실제 ICU 안에서 측정된 이벤트 데이터도 이 3000 stay에 맞게 잘 잘려 있나?")
print("chartevents stay_id not in icustays:", len(missing_in_icustays))
print("==============================================")

==============================================
Unique stay_id in icustays    : 3000
Unique stay_id in chartevents : 3000
실제 ICU 안에서 측정된 이벤트 데이터도 이 3000 stay에 맞게 잘 잘려 있나?
chartevents stay_id not in icustays: 0
==============================================

In [5]:
# ------------------------------------------------------------------------------
# Load `inputevents.csv.gz` & check event matches well
# ------------------------------------------------------------------------------
inputevents_path = ICU_DIR / "inputevents.csv.gz"
inputevents = pd.read_csv(inputevents_path)

print("==============================================")
print("inputevetns shape:", inputevents.shape)
print("columns:")
print(inputevents.columns.tolist())
print("==============================================")
print(inputevents.head())
print()
print("==============================================")


icu_stay_ids = set(icustays["stay_id"].dropna().unique())
input_stay_ids = set(inputevents["stay_id"].dropna().unique())
missing_input_stays = input_stay_ids - icu_stay_ids
stays_without_inputevents = icu_stay_ids - input_stay_ids

print("Unique stay_id in icustays    :", len(icu_stay_ids))
print("Unique stay_id in inputevents :", len(input_stay_ids))
print("inputevents stay_id들이 3000 stay에 맞게 잘 잘려 있나?")
print("inputevents stay_id not in icustays:", len(missing_input_stays))
print("ICU stays without inputevents       :", len(stays_without_inputevents))
print("==============================================")

==============================================
inputevetns shape: (813092, 26)
columns:
['subject_id', 'hadm_id', 'stay_id', 'caregiver_id', 'starttime', 'endtime', 'storetime', 'itemid', 'amount', 'amountuom', 'rate', 'rateuom', 'orderid', 'linkorderid', 'ordercategoryname', 'secondaryordercategoryname', 'ordercomponenttypedescription', 'ordercategorydescription', 'patientweight', 'totalamount', 'totalamountuom', 'isopenbag', 'continueinnextdept', 'statusdescription', 'originalamount', 'originalrate']
==============================================
   subject_id   hadm_id   stay_id  caregiver_id            starttime  \
0    10001884  26184834  37510196          3178  2131-01-11 05:50:00
1    10001884  26184834  37510196          3178  2131-01-11 06:39:00
2    10001884  26184834  37510196          3178  2131-01-11 06:39:00
3    10001884  26184834  37510196          3178  2131-01-11 06:49:00
4    10001884  26184834  37510196          3178  2131-01-11 06:49:00

               endtime            storetime  itemid      amount amountuom  \
0  2131-01-11 05:51:00  2131-01-11 06:50:00  221744   24.999999       mcg
1  2131-01-11 07:47:00  2131-01-11 06:48:00  222168  221.354167        mg
2  2131-01-11 07:47:00  2131-01-11 06:48:00  225943   22.135415        mL
3  2131-01-12 03:50:00  2131-01-11 06:49:00  225158  210.166673        mL
4  2131-01-13 08:49:00  2131-01-13 09:16:00  225158  500.000015        mL

   ...  ordercomponenttypedescription ordercategorydescription  patientweight  \
0  ...           Main order parameter                Drug Push           65.0
1  ...           Main order parameter           Continuous Med           65.0
2  ...                 Mixed solution           Continuous Med           65.0
3  ...           Main order parameter            Continuous IV           65.0
4  ...           Main order parameter            Continuous IV           65.0

   totalamount totalamountuom isopenbag continueinnextdept statusdescription  \
0          NaN            NaN         0                  0   FinishedRunning
1        100.0             mL         0                  0   ChangeDose/Rate
2        100.0             mL         0                  0   ChangeDose/Rate
3        500.0             mL         0                  0           Stopped
4        500.0             mL         0                  0   FinishedRunning

   originalamount  originalrate
0        25.00000     25.000000
1       664.06250     50.000004
2        66.40625     19.480501
3       500.00000     10.000000
4       500.00000     10.000000

[5 rows x 26 columns]

==============================================
Unique stay_id in icustays    : 3000
Unique stay_id in inputevents : 2535
inputevents stay_id들이 3000 stay에 맞게 잘 잘려 있나?
inputevents stay_id not in icustays: 0
ICU stays without inputevents       : 465
==============================================

In [6]:
# ------------------------------------------------------------------------------
# Load `labevents.csv.gz` & check item matches well
# ------------------------------------------------------------------------------
labevents_path = HOSP_DIR / "labevents.csv.gz"
labevents = pd.read_csv(labevents_path)

print("==============================================")
print("labevents shape:", labevents.shape)
print("columns:")
print(labevents.columns.tolist())
print("==============================================")
print(labevents.head())

/tmp/ipykernel_591/2762859370.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  labevents = pd.read_csv(labevents_path)

==============================================
labevents shape: (3508887, 16)
columns:
['labevent_id', 'subject_id', 'hadm_id', 'specimen_id', 'itemid', 'order_provider_id', 'charttime', 'storetime', 'value', 'valuenum', 'valueuom', 'ref_range_lower', 'ref_range_upper', 'flag', 'priority', 'comments']
==============================================
   labevent_id  subject_id   hadm_id  specimen_id  itemid order_provider_id  \
0        19996    10001884  26184834     14927112   51221               NaN
1        19997    10001884  26184834     14927112   51222               NaN
2        19998    10001884  26184834     14927112   51248               NaN
3        19999    10001884  26184834     14927112   51249               NaN
4        20000    10001884  26184834     14927112   51250               NaN

             charttime            storetime value  valuenum valueuom  \
0  2131-01-08 05:11:00  2131-01-08 08:21:00  35.6      35.6        %
1  2131-01-08 05:11:00  2131-01-08 08:21:00  11.4      11.4     g/dL
2  2131-01-08 05:11:00  2131-01-08 08:21:00  28.2      28.2       pg
3  2131-01-08 05:11:00  2131-01-08 08:21:00  32.0      32.0     g/dL
4  2131-01-08 05:11:00  2131-01-08 08:21:00    88      88.0       fL

   ref_range_lower  ref_range_upper flag priority comments
0             34.0             45.0  NaN  ROUTINE      NaN
1             11.2             15.7  NaN  ROUTINE      NaN
2             26.0             32.0  NaN  ROUTINE      NaN
3             32.0             37.0  NaN  ROUTINE      NaN
4             82.0             98.0  NaN  ROUTINE      NaN

In [7]:
lab_subject_ids = set(labevents["subject_id"].dropna().unique())
lab_hadm_ids = set(labevents["hadm_id"].dropna().unique())

subset_subject_ids = set(patients["subject_id"].dropna().unique())
subset_hadm_ids = set(admissions["hadm_id"].dropna().unique())

lab_subject_not_in_subset = lab_subject_ids - subset_subject_ids
lab_hadm_not_in_subset = lab_hadm_ids - subset_hadm_ids

print("==============================================")
print("labevents.csv.gz의 subjects와 admissions들이 patients/admissions.csv.gz와 매칭되는가?")
print("labevents subject_id not in patients:", len(lab_subject_not_in_subset))
print("labevents hadm_id not in admissions:", len(lab_hadm_not_in_subset))
print("==============================================")

==============================================
labevents.csv.gz의 subjects와 admissions들이 patients/admissions.csv.gz와 매칭되는가?
labevents subject_id not in patients: 0
labevents hadm_id not in admissions: 0
==============================================

In [8]:
# ------------------------------------------------------------------------------
# Load `d_items/d_labitems.csv.gz` & check item matches well
# ------------------------------------------------------------------------------
d_items_path = ICU_DIR / "d_items.csv.gz"
d_labitems_path = HOSP_DIR / "d_labitems.csv.gz"
d_items = pd.read_csv(d_items_path)
d_labitems = pd.read_csv(d_labitems_path)

print("==============================================")
print("d_items shape: ", d_items.shape)
print("d_labitems shape: ", d_labitems.shape)
print("==============================================")
print("d_items columns:")
print(d_items.columns.tolist())

print("\nd_labitems columns:")
print(d_labitems.columns.tolist())
print("==============================================")

==============================================
d_items shape:  (4095, 9)
d_labitems shape:  (1650, 4)
==============================================
d_items columns:
['itemid', 'label', 'abbreviation', 'linksto', 'category', 'unitname', 'param_type', 'lownormalvalue', 'highnormalvalue']

d_labitems columns:
['itemid', 'label', 'fluid', 'category']
==============================================

In [9]:
# ICU dictionary itemid
d_item_ids = set(d_items["itemid"].dropna().unique())

# LAB dictionary itemid
d_labitem_ids = set(d_labitems["itemid"].dropna().unique())


# chartevents에 있는데 d_items에는 없는 itemid
chart_item_ids = set(chartevents["itemid"].dropna().unique())
missing_chart_items = chart_item_ids - d_item_ids
print("Unique itemid not in chartevents: ", len(missing_chart_items))

# inputevents에 있는데 d_items에는 없는 itemid
input_item_ids = set(inputevents["itemid"].dropna().unique())
missing_input_items = input_item_ids - d_item_ids
print("Unique itemid not in d_items: ", len(missing_input_items))

# labevents에 있는데 d_labitems에는 없는 itemid
lab_item_ids = set(labevents["itemid"].dropna().unique())
missing_lab_items = lab_item_ids - d_labitem_ids
print("Unique itemid not in d_labitems: ", len(missing_lab_items))

Unique itemid not in chartevents:  0
Unique itemid not in d_items:  0
Unique itemid not in d_labitems:  0

In [10]:
# ------------------------------------------------------------------------------
# Check ICU's timestamp
# ------------------------------------------------------------------------------
print("==============================================")
icustays["intime"] = pd.to_datetime(icustays["intime"])
icustays["outtime"] = pd.to_datetime(icustays["outtime"])

invalid_stay_time = icustays[icustays["outtime"] <= icustays["intime"]]
print("outtime이 intime보다 앞에 있는 경우: ", len(invalid_stay_time))
print("==============================================")
calculated_los = (icustays["outtime"] - icustays["intime"]).dt.total_seconds() / (24 * 60 * 60)

los_diff = (calculated_los - icustays["los"]).abs()
print("Max los difference: ", los_diff.max())
print("Min los difference: ", los_diff.min())
print("==============================================")

==============================================
outtime이 intime보다 앞에 있는 경우:  0
==============================================
Max los difference:  7.105427357601002e-15
Min los difference:  0.0
==============================================

In [11]:
# ------------------------------------------------------------------------------
# Check chartevent's charttime
# ------------------------------------------------------------------------------
chartevents["charttime"] = pd.to_datetime(chartevents["charttime"], errors="coerce")

print("Invalid chartevents charttime:", chartevents["charttime"].isna().sum())

Invalid chartevents charttime: 0

In [12]:
# ------------------------------------------------------------------------------
# Check inputevents's timestamp
# ------------------------------------------------------------------------------
inputevents["starttime"] = pd.to_datetime(inputevents["starttime"], errors="coerce")
inputevents["endtime"] = pd.to_datetime(inputevents["endtime"], errors="coerce")

print("Invalid input starttime:", inputevents["starttime"].isna().sum())
print("Invalid input endtime:", inputevents["endtime"].isna().sum())
print("endtime < starttime:", (inputevents["endtime"] < inputevents["starttime"]).sum())

Invalid input starttime: 0
Invalid input endtime: 0
endtime < starttime: 2

In [13]:
# inputevents에서 endtime이 starttime보다 앞에 있는 경우 조사
invalid_input_time = inputevents[inputevents["endtime"] < inputevents["starttime"]].copy()

print("Invalid rows: ", len(invalid_input_time))
print()
display(
    invalid_input_time[
        [
            "subject_id",
            "hadm_id",
            "stay_id",
            "itemid",
            "starttime",
            "endtime",
            "storetime",
            "amount",
            "amountuom",
            "rate",
            "rateuom",
            "ordercategoryname",
            "statusdescription",
        ]
    ]
)

Invalid rows:  2

,subject_id,hadm_id,stay_id,itemid,starttime,endtime,storetime,amount,amountuom,rate,rateuom,ordercategoryname,statusdescription
252993,13188363,24879827,32837061,222168,2152-05-07 17:30:00,2152-05-07 17:29:00,2152-05-07 17:30:00,-2.159342,mg,32.717310,mcg/kg/min,01-Drips,FinishedRunning
252994,13188363,24879827,32837061,225943,2152-05-07 17:30:00,2152-05-07 17:29:00,2152-05-07 17:30:00,-0.215934,mL,12.956053,mL/hour,01-Drips,FinishedRunning

In [22]:
# ------------------------------------------------------------------------------
# Check variables for CF state annotation
# ------------------------------------------------------------------------------

# MAP 관련 variable 찾기
map_candidates = d_items[
    d_items["label"].str.contains("blood pressure mean|mean blood pressure|arterial blood pressure mean",
    case=False, na=False, regex=True)][["itemid", "label", "abbreviation", "linksto", "category", "unitname"]]

display(map_candidates)

,itemid,label,abbreviation,linksto,category,unitname
8,220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg
26,220181,Non Invasive Blood Pressure mean,NBPm,chartevents,Routine Vital Signs,mmHg

In [23]:
map_itemids = set(map_candidates["itemid"])

map_event_count = chartevents["itemid"].isin(map_itemids).sum()
map_stay_count = chartevents.loc[chartevents["itemid"].isin(map_itemids), "stay_id"].nunique()

print("MAP candidate event rows :", map_event_count)
print("MAP candidate stays      :", map_stay_count)

MAP candidate event rows : 575294
MAP candidate stays      : 2993

In [24]:
# 혈압 관련 항목 전체
bp_candidates = d_items[
    d_items["label"].str.contains(
        "blood pressure",
        case=False,
        na=False
    )
][
    ["itemid", "label", "abbreviation", "linksto", "category", "unitname"]
]

display(bp_candidates)

,itemid,label,abbreviation,linksto,category,unitname
6,220050,Arterial Blood Pressure systolic,ABPs,chartevents,Routine Vital Signs,mmHg
7,220051,Arterial Blood Pressure diastolic,ABPd,chartevents,Routine Vital Signs,mmHg
8,220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg
9,220056,Arterial Blood Pressure Alarm - Low,ABP Alarm - Low,chartevents,Alarms,mmHg
10,220058,Arterial Blood Pressure Alarm - High,ABP Alarm - High,chartevents,Alarms,mmHg
24,220179,Non Invasive Blood Pressure systolic,NBPs,chartevents,Routine Vital Signs,mmHg
25,220180,Non Invasive Blood Pressure diastolic,NBPd,chartevents,Routine Vital Signs,mmHg
26,220181,Non Invasive Blood Pressure mean,NBPm,chartevents,Routine Vital Signs,mmHg
330,223751,Non-Invasive Blood Pressure Alarm - High,NBP Alarm - High,chartevents,Alarms,mmHg
331,223752,Non-Invasive Blood Pressure Alarm - Low,NBP Alarm - Low,chartevents,Alarms,mmHg
575,224167,Manual Blood Pressure Systolic Left,Manual BPs L,chartevents,Routine Vital Signs,mmHg
768,224643,Manual Blood Pressure Diastolic Left,Manual BPd L,chartevents,Routine Vital Signs,mmHg
2154,227242,Manual Blood Pressure Diastolic Right,Manual BPd R,chartevents,Routine Vital Signs,mmHg
2155,227243,Manual Blood Pressure Systolic Right,Manual BPs R,chartevents,Routine Vital Signs,mmHg
2267,227537,ART Blood Pressure Alarm - High,ART BP Alarm - High,chartevents,Alarms,mmHg
2268,227538,ART Blood Pressure Alarm - Low,ART BP Alarm - Low,chartevents,Alarms,mmHg
2269,227539,ART Blood Pressure Alarm Source,ART BP Alarm Source,chartevents,Alarms,NaN

In [17]:
# Lactate 후보
lactate_candidates = d_labitems[
    d_labitems["label"].str.contains("lactate",
    case=False, na=False)][["itemid", "label", "fluid", "category"]]

display(lactate_candidates)

      itemid                           label                fluid   category
11     50813                         Lactate                Blood  Blood Gas
41     50843  Lactate Dehydrogenase, Ascites              Ascites  Chemistry
151    50954      Lactate Dehydrogenase (LD)                Blood  Chemistry
242    51054  Lactate Dehydrogenase, Pleural              Pleural  Chemistry
911    51795      Lactate Dehydrogenase, CSF  Cerebrospinal Fluid  Chemistry
1035   51944    Lactate Dehydrogenase, Stool                Stool  Chemistry
1516   52442                         Lactate                Blood  Blood Gas
1615   53154                         Lactate                Blood  Chemistry

In [20]:
lactate_itemids = set(lactate_candidates["itemid"])

lactate_event_count = labevents["itemid"].isin(lactate_itemids).sum()
lactate_subject_count = labevents.loc[
    labevents["itemid"].isin(lactate_itemids),
    "subject_id"
].nunique()
lactate_hadm_count = labevents.loc[
    labevents["itemid"].isin(lactate_itemids),
    "hadm_id"
].nunique()

print("Lactate candidate event rows :", lactate_event_count)
print("Lactate candidate subjects   :", lactate_subject_count)
print("Lactate candidate admissions :", lactate_hadm_count)

Lactate candidate event rows : 56563
Lactate candidate subjects   : 2788
Lactate candidate admissions : 2879

In [18]:
# Vasoactive, Intropic drug 후보
drug_pattern = ("norepinephrine|epinephrine|vasopressin|"
                "dobutamine|dopamine|milrinone|phenylephrine")

drug_candidates = d_items[
    d_items["label"].str.contains(
        drug_pattern,
        case=False, na=False, regex=True
    )][["itemid", "label", "abbreviation", "linksto", "category", "unitname"]]

display(drug_candidates)

,itemid,label,abbreviation,linksto,category,unitname
280,221289,Epinephrine,Epinephrine,inputevents,Medications,mg
292,221653,Dobutamine,Dobutamine,inputevents,Medications,mg
293,221662,Dopamine,Dopamine,inputevents,Medications,mg
299,221749,Phenylephrine,Phenylephrine,inputevents,Medications,mg
305,221906,Norepinephrine,Norepinephrine,inputevents,Medications,mg
306,221986,Milrinone,Milrinone,inputevents,Medications,mg
318,222315,Vasopressin,Vasopressin,inputevents,Medications,units
3737,229617,Epinephrine.,Epinephrine.,inputevents,Medications,mg
3746,229630,Phenylephrine (50/250),Phenylephrine (50/250),inputevents,Medications,mg
3747,229631,Phenylephrine (200/250)_OLD_1,Phenylephrine (200/250)_OLD_1,inputevents,Medications,mg
3748,229632,Phenylephrine (200/250),Phenylephrine (200/250),inputevents,Medications,mg
3870,229789,Phenylephrine (Intubation),Phenylephrine (Intubation),chartevents,Intubation,mcg

In [21]:
drug_itemids = set(drug_candidates["itemid"])

drug_event_count = inputevents["itemid"].isin(drug_itemids).sum()
drug_stay_count = inputevents.loc[
    inputevents["itemid"].isin(drug_itemids),
    "stay_id"
].nunique()

print("Drug candidate event rows :", drug_event_count)
print("Drug candidate stays      :", drug_stay_count)

Drug candidate event rows : 56576
Drug candidate stays      : 1435